### ISSUE TITLE
incomparable with fish shell due to use of "&&" as combiner

### ISSUE THREAD

**Issue by XedMada** [flipxfx/neovim-iterm-app#1]
Using app with fish shell results in error:
"Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'."

This is due to fish shell's somewhat controversial combiner implementation outlined [here](http://fishshell.com/docs/current/tutorial.html#tut_combiners)

**Comment by flipxfx** [comment]
I've never heard of fish. If you'd like to submit a pull request so it works with both feel free, but I'm not sure how you would know which too use or maybe there is a way for the same command to work for both?
